CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    roles VARCHAR(255) NOT NULL
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price FLOAT NOT NULL,
    category VARCHAR(255)
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_id BIGINT,
    rating INTEGER NOT NULL,
    comment VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_list VARCHAR(255),
    total_amount FLOAT NOT NULL,
    order_date TIMESTAMP NOT NULL,
    status VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES app_user(id)
);
